export enum REQUEST_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECT = "REJECT",
  DELETED = "DELETED",
  CANCEL = "CANCEL",
}

export enum REQUEST_TYPE {
  ARCHIVE = "ARCHIVE",
  DELETE = "DELETE",
  EDIT = "EDIT",
  UNDELETE = "UNDELETE",
  UNARCHIVE = "UNARCHIVE",
}
