export enum SELECT_CATEGORY_LEVELS {
  CREATE_ESTATE = "CREATE_ESTATE",
  SUB_REGION = "SUB_REGION",
  REGION = "REGION",
  PROPERTY_TYPE = "PROPERTY_TYPE",
  MAIN_CATEGORY = "MAIN_CATEGORY",
  DEAL_TYPE = "DEAL_TYPE",
}

export const selectCategoryLevels = [
  SELECT_CATEGORY_LEVELS.DEAL_TYPE,
  SELECT_CATEGORY_LEVELS.MAIN_CATEGORY,
  SELECT_CATEGORY_LEVELS.PROPERTY_TYPE,
  SELECT_CATEGORY_LEVELS.REGION,
  SELECT_CATEGORY_LEVELS.SUB_REGION,
  SELECT_CATEGORY_LEVELS.CREATE_ESTATE,
];
