export enum ESTATE_STATUS {
  PENDING = "PENDING",
  PUBLISH = "PUBLISH",
}

export enum ESTATE_ARCHIVE_STATUS {
  ARCHIVE = "ARCHIVE",
  DELETE = "DELETE",
}

export enum FILTER_ESTATE_STATUS {
  PUBLISH = "PUBLISH",
  PENDING = "PENDING",
  ARCHIVE = "ARCHIVE",
  DELETE = "DELETE",
  REQUEST_ARCHIVE = "REQUEST_ARCHIVE",
  REQUEST_DELETE = "REQUEST_DELETE",
}
